/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 18:12:59 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl2.Library;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Library_ESTest extends Library_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Library library0 = new Library();
      library0.extend("@Vg9>!jm-EB2-jJ]", "@Vg9>!jm-EB2-jJ]");
      library0.addReference("L]A{!|!iQw1? iS,k_", 0);
      try { 
        library0.addMagazine("L]A{!|!iQw1? iS,k_", 0, 0, 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // the magazine has already added
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Library library0 = new Library();
      String string0 = null;
      library0.addReference("U>%;oI7(vbqkCINoSyg", (-3082));
      int int0 = 0;
      // Undeclared exception!
      try { 
        library0.addBook((String) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("4W(:qxLH<r))N9#*");
      library0.timePass(3706);
      library0.returnDocument("4W(:qxLH<r))N9#*", "");
      library0.getTotalPenalty("");
      library0.addProfMember("");
      library0.returnDocument("", "ir.ramtung.impl2.Book");
      library0.getTotalPenalty("ir.ramtung.impl2.Book");
      library0.borrow("ir.ramtung.impl2.Person", "");
      library0.addProfMember("ir.ramtung.impl2.Book");
      try { 
        library0.addReference(" ", 897);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // reference name is empty
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Library library0 = new Library();
      library0.availableTitles();
      try { 
        library0.addMagazine("blMW3}7z\"),?cg@Z", (-1240), 2153, 532);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // magazine`s year is incorrect
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference("ir.ramtung.impl2.Student", 2);
      library0.availableTitles();
      library0.extend("ir.ramtung.impl2.Student", "[>Ip\nOC;SdK ");
      library0.addMagazine("[>Ip\nOC;SdK ", 2, 2, 0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.addMagazine("", 1, (-1), 1);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // magazine`s number is incorrect
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Library library0 = new Library();
      String string0 = "magazine name is empty";
      int int0 = 0;
      library0.addBook("S:$[", 0);
      library0.addBook("magazine name is empty", (-1948));
      try { 
        library0.addReference("magazine name is empty", (-164));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // the reference has already added
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.addMagazine("ir.ramtung.impl2.Prof", 0, (-6613), (-6613));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // magazine`s year is incorrect
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("TujN4bF");
      int int0 = 1912;
      String string0 = "yetI|y$mc?*O";
      library0.extend("yetI|y$mc?*O", "TujN4bF");
      library0.extend("TujN4bF", "TujN4bF");
      library0.addBook("TujN4bF", 1912);
      library0.addBook("_", 1912);
      library0.extend("TujN4bF", "_");
      String string1 = "Cgrzkb'\"Zn";
      library0.returnDocument("Cgrzkb'\"Zn", "TujN4bF");
      String string2 = ",<p";
      // Undeclared exception!
      try { 
        library0.addStudentMember((String) null, ",<p");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("ir.ramtung.impl2.Document");
      String string0 = null;
      // Undeclared exception!
      try { 
        library0.addProfMember((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("the member cant borrow any more", 2672, 2672, 2672);
      library0.addBook("", 21);
      library0.getTotalPenalty("");
      String string0 = "the book has already added";
      library0.borrow("the book has already added", "the book has already added");
      try { 
        library0.timePass((-3989));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // days cant be negative
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Library library0 = new Library();
      library0.getTotalPenalty("UpQHQc{>Lng");
      library0.availableTitles();
      try { 
        library0.addStudentMember("j#W|cQ(i:XjgHN(", "");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // student name is empty
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.timePass((-1555));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // days cant be negative
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Library library0 = new Library();
      // Undeclared exception!
      try { 
        library0.addReference((String) null, 627);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("W8kTi|o;bf=-'rn");
      library0.availableTitles();
      library0.addBook("ir.ramtung.impl2.Document", 0);
      library0.addStudentMember("rVPWt", "ir.ramtung.impl2.Document");
      String string0 = null;
      try { 
        library0.borrow("ir.ramtung.impl2.Document", "ir.ramtung.impl2.Document");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // this book doesnt exist
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Library library0 = new Library();
      String string0 = "";
      library0.addProfMember("");
      library0.availableTitles();
      library0.getTotalPenalty("");
      library0.returnDocument("", "s~`\".I\"4CqyKBy2t+HD");
      library0.availableTitles();
      library0.addReference("T=&4K7D.aL", 0);
      // Undeclared exception!
      try { 
        library0.addMagazine((String) null, (-584), 0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("");
      // Undeclared exception!
      try { 
        library0.borrow("", "");
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("");
      library0.returnDocument("the reference has already added", "");
      library0.timePass(0);
      library0.returnDocument("", "");
      library0.availableTitles();
      library0.getTotalPenalty("the reference has already added");
      library0.addBook("", 0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("1", "1");
      library0.returnDocument((String) null, (String) null);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook("", (-1));
      library0.getTotalPenalty((String) null);
      try { 
        library0.borrow("pl>t:i34P*", "");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // this book doesnt exist
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Library library0 = new Library();
      library0.availableTitles();
      try { 
        library0.addMagazine(" ", 1, 1, 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // magazine name is empty
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Library library0 = new Library();
      library0.availableTitles();
      library0.availableTitles();
      library0.availableTitles();
      try { 
        library0.addStudentMember("", "");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // student id is empty
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("Z'sY-%1G+4G#");
      library0.extend("Z'sY-%1G+4G#", "50I");
      String string0 = "ir.ramtung.sts01.LibraryException";
      try { 
        library0.addStudentMember("50I", "Z'sY-%1G+4G#");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // the member has already added
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook("the magazine has already added", (-2004318069));
      library0.availableTitles();
      library0.addProfMember("the magazine has already added");
      int int0 = 3881;
      library0.timePass(3881);
      String string0 = "ir.ramtung.impl2.Person";
      library0.extend("ir.ramtung.impl2.Person", "*'ol\"F&'<;6{");
      library0.addStudentMember("p4x_mQlXPx:0_95^", "cant extend");
      library0.extend("*'ol\"F&'<;6{", "U>");
      library0.extend("U>", "the magazine has already added");
      library0.getTotalPenalty("the magazine has already added");
      library0.availableTitles();
      // Undeclared exception!
      library0.timePass(3881);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook("M Z(|Vr", 13);
      library0.addStudentMember("d9bHe/FPo^)", "d9bHe/FPo^)");
      library0.borrow("d9bHe/FPo^)", "d9bHe/FPo^)");
      library0.addStudentMember("ir.ramtung.sts01.LibraryException", "ir.ramtung.sts01.LibraryException");
      try { 
        library0.extend("d9bHe/FPo^)", (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // cant extend
         //
         verifyException("ir.ramtung.impl2.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Library library0 = new Library();
      library0.borrow("Lj Y]72kgX@/K", "Lj Y]72kgX@/K");
      library0.addProfMember("Lj Y]72kgX@/K");
      library0.timePass(583);
      library0.getTotalPenalty("!XIt.G)");
      library0.getTotalPenalty("Lj Y]72kgX@/K");
      library0.addReference("Lj Y]72kgX@/K", (-1947));
      try { 
        library0.addReference("Lj Y]72kgX@/K", (-2049870752));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // the reference has already added
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("U2%Q_KA=W9xK-");
      library0.extend("U2%Q_KA=W9xK-", "U2%Q_KA=W9xK-");
      library0.getTotalPenalty("xk;t3Ge-.ChuYkq7K:");
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Library library0 = new Library();
      library0.getTotalPenalty("ir.ramtung.impl2.Book");
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Library library0 = new Library();
      int int0 = 2;
      library0.addBook("the magazine has already added", 2);
      library0.returnDocument("the magazine has already added", "the magazine has already added");
      library0.timePass(2);
      library0.extend("the magazine has already added", "the magazine has already added");
      String string0 = "";
      library0.addBook("", 21);
      library0.borrow("the magazine has already added", "");
      library0.borrow("the magazine has already added", "");
      library0.borrow("the reference has already added", "the magazine has already added");
      library0.addBook("the reference has already added", 3000);
      String string1 = "9V";
      try { 
        library0.addProfMember(" ");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // prof name is empty
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Library library0 = new Library();
      library0.extend("M Z(|Vr", (String) null);
      library0.addBook("M Z(|Vr", 13);
      library0.addStudentMember("d9bHe/FPo^)", "d9bHe/FPo^)");
      library0.borrow("d9bHe/FPo^)", "d9bHe/FPo^)");
      library0.addStudentMember("ir.ramtung.sts01.LibraryException", "ir.ramtung.sts01.LibraryException");
      library0.availableTitles();
      String string0 = "";
      try { 
        library0.addBook(" ", 3384);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // book name is empty
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Library library0 = new Library();
      int int0 = 2;
      library0.addBook("the magazine has already added", 2);
      library0.returnDocument("the magazine has already added", "the magazine has already added");
      library0.addStudentMember("ir.ramtung.impl2.Book", "the magazine has already added");
      library0.timePass(2);
      library0.extend("the magazine has already added", "the magazine has already added");
      String string0 = "";
      library0.addBook("", 21);
      library0.borrow("the magazine has already added", "");
      library0.borrow("the magazine has already added", "");
      library0.addMagazine("ir.ramtung.impl2.Book", 21, 2, 21);
      try { 
        library0.borrow("the magazine has already added", "the magazine has already added");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // the member cant borrow any more
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Library library0 = new Library();
      library0.borrow("A$pQYH]%./e5wX", "magazine`s year is incorrect");
      library0.timePass(0);
      library0.borrow("", "");
      library0.getTotalPenalty(")FzY!E ");
      library0.borrow("95zcH+ZW`dL8V:-V>~", (String) null);
      library0.addBook("ir.ramtung.impl2.Book", 0);
      library0.borrow((String) null, (String) null);
      library0.extend((String) null, "0Q!=-Yf/d`P-t/'VG=");
      library0.availableTitles();
      library0.extend("", (String) null);
      library0.timePass(0);
      library0.borrow("the member cant borrom any more", "magazine`s year is incorrect");
      String string0 = " ";
      library0.addReference("the member cant borrow any more", (-1));
      try { 
        library0.addReference(" ", 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // reference name is empty
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Library library0 = new Library();
      int int0 = 2;
      library0.addReference("", 2);
      try { 
        library0.addMagazine("", 425, (-215), (-779));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // the magazine has already added
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Library library0 = new Library();
      library0.getTotalPenalty("ir.ramtung.sts01.LibraryException");
      String string0 = "Sdv0";
      library0.addStudentMember("Sdv0", "06FV");
      library0.getTotalPenalty("ir.ramtung.impl2.Magazine");
      library0.addStudentMember("ir.ramtung.sts01.LibraryException", "ir.ramtung.impl2.Magazine");
      library0.addStudentMember("magazine name is empty", "magazine name is empty");
      library0.addReference("ir.ramtung.sts01.LibraryException", 0);
      library0.extend("magazine name is empty", "]8Spzr");
      library0.availableTitles();
      library0.getTotalPenalty((String) null);
      try { 
        library0.addMagazine("06FV", (-1397), 1, 1016);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // magazine`s year is incorrect
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Library library0 = new Library();
      library0.getTotalPenalty("ir.ramtung.sts01.LibraryException");
      String string0 = "Sdv0";
      library0.addStudentMember("Sdv0", "06FV");
      library0.getTotalPenalty("ir.ramtung.impl2.Magazine");
      library0.addStudentMember("ir.ramtung.sts01.LibraryException", "ir.ramtung.impl2.Magazine");
      library0.addStudentMember("magazine name is empty", "magazine name is empty");
      library0.addStudentMember("ir.ramtung.sts01.LibraryException", "ir.ramtung.impl2.Document");
      library0.addReference("ir.ramtung.sts01.LibraryException", 0);
      library0.extend("magazine name is empty", "]8Spzr");
      library0.availableTitles();
      library0.borrow((String) null, "+5U`9VFbfw;5vn");
      library0.getTotalPenalty((String) null);
      try { 
        library0.addMagazine("06FV", (-1397), (-1397), 1016);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // magazine`s year is incorrect
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("(T,ow,", "(T,ow,");
      library0.getTotalPenalty("(T,ow,");
      library0.addStudentMember("(T,ow,", "`j|pMbE>jjZr/Yf");
      library0.getTotalPenalty("cV.a");
      library0.timePass(0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook("cant extend", (-2322));
      int int0 = 0;
      library0.availableTitles();
      try { 
        library0.addReference("cant extend", 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // the reference has already added
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook("ir.ramtung.impl2.Student", 0);
      library0.addBook("ir.ramtung.impl2.Document", 0);
      library0.timePass(21);
      library0.borrow("O'f>/", "");
      library0.addStudentMember("ir.ramtung.impl2.Document", "O'f>/");
      library0.extend("8H`A[t*{AuY", "");
      library0.extend((String) null, "GHa,)%LDBqB:Ce_uv");
      library0.addBook("cV.a", 0);
      library0.returnDocument("O'f>/", "the magazine has already added");
      library0.addBook("6lE0`pf7rP%8N", 2488);
      library0.availableTitles();
      library0.returnDocument("the magazine has already added", "e }f[R|+H]M~-9OJ");
      library0.borrow("the magazine has already added", " ");
      library0.addReference("the magazine has already added", (-1865));
      try { 
        library0.addMagazine(" ", (-541), 0, (-541));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // magazine name is empty
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Library library0 = new Library();
      String string0 = "U+%CC|%Z{q";
      library0.addReference("U+%CC|%Z{q", 0);
      String string1 = "";
      String string2 = "ml";
      library0.availableTitles();
      library0.returnDocument("", "ml");
      try { 
        library0.addMagazine("", 1994, 0, 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // magazine`s number is incorrect
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Library library0 = new Library();
      library0.returnDocument("6", "MBoB_&:KZ:");
      library0.getTotalPenalty("6");
      library0.addProfMember("");
      library0.addProfMember("6");
      library0.extend("D", "Mtsz>Dx'JxI|yZK");
      library0.extend("the member cant borrow any more", "+a6");
      library0.addReference("ir.ramtung.sts01.LibraryException", 0);
      library0.availableTitles();
      library0.addMagazine("Jx>b&", 1, 1188, 1390);
      library0.availableTitles();
      library0.extend("ir.ramtung.impl2.Prof", "6");
      library0.returnDocument("{", "6");
      library0.returnDocument("", "");
      library0.timePass(998);
      library0.addProfMember(" D%0#(P");
      library0.addBook("", 0);
      library0.returnDocument("+a6", "Jx>b&");
      library0.getTotalPenalty((String) null);
      library0.borrow("", "17F!H39l6iy1wGCN");
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook("student name is empty", 1138);
      library0.extend("student name is empty", "oYKm]");
      library0.returnDocument("ir.ramtung.impl2.Person", "book name is empty");
      library0.addReference("book name is empty", (-1));
      library0.addProfMember("xHq@!sS-ftA^gDh");
      library0.addStudentMember("ir.ramtung.impl2.Document", "student name is empty");
      library0.extend("SOm.3Q", "ir.ramtung.impl2.Person");
      library0.borrow("xHq@!sS-ftA^gDh", "i2$??pbqF'K}l");
      library0.addStudentMember("P+|!:EP\"~tjyZc", "the member cant borrow any more");
      try { 
        library0.addProfMember("the member cant borrow any more");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // the member has already added
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Library library0 = new Library();
      int int0 = 2;
      library0.addBook("the magazine has already added", 2);
      library0.returnDocument("the magazine has already added", "the magazine has already added");
      library0.addStudentMember("ir.ramtung.impl2.Book", "the magazine has already added");
      library0.timePass(2);
      library0.extend("the magazine has already added", "the magazine has already added");
      String string0 = "";
      library0.addBook("", 21);
      library0.borrow("the magazine has already added", "");
      library0.borrow("the magazine has already added", "");
      library0.addMagazine("the reference has already added", 21, 2, 21);
      library0.borrow("the reference has already added", "the magazine has already added");
      try { 
        library0.addBook("the reference has already added", 3000);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // the book has already added
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Library library0 = new Library();
      library0.timePass(951);
      library0.addStudentMember("4<D,{[_(s|=hxa3@sx", "l97$!]xVQ<~");
      library0.availableTitles();
      library0.availableTitles();
      library0.returnDocument("4<D,{[_(s|=hxa3@sx", "4<D,{[_(s|=hxa3@sx");
      int int0 = 458;
      String string0 = "";
      library0.returnDocument("l97$!]xVQ<~", "");
      library0.timePass(458);
      try { 
        library0.addStudentMember("l97$!]xVQ<~", "l97$!]xVQ<~");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // the member has already added
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Library library0 = new Library();
      String string0 = "ir.ramtung.impl2.Person";
      library0.getTotalPenalty("ir.ramtung.impl2.Person");
      String string1 = "";
      try { 
        library0.addStudentMember("", "Uyk");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // student id is empty
         //
         verifyException("ir.ramtung.impl2.Library", e);
      }
  }
}
